# Generated by Django 3.0.5 on 2020-05-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('die_1_value', models.IntegerField()),
                ('die_2_value', models.IntegerField()),
            ],
        ),
    ]
