# Generated by Django 3.0.5 on 2020-05-10 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0002_auto_20200510_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roll',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='games.Action')),
                ('num_shakes', models.IntegerField()),
            ],
            bases=('games.action',),
        ),
    ]
