# Generated by Django 3.0.5 on 2020-05-06 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roll',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='games.Action')),
                ('die_1_value', models.IntegerField()),
                ('die_2_value', models.IntegerField()),
            ],
            bases=('games.action',),
        ),
    ]
