# Generated by Django 3.0.5 on 2020-05-06 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_dice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roll',
            name='die_1_value',
        ),
        migrations.RemoveField(
            model_name='roll',
            name='die_2_value',
        ),
        migrations.AddField(
            model_name='roll',
            name='num_shakes',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
