version: '3'

services:
    application:
        build: ../app
        volumes:
            - "../app/config/dev:/app/config"
        ports:
            - "8000:8000"
        command: bash -c "python manage.py runserver 0.0.0.0:8000"
