version: '3'

services:
    application:
        build: ../app
        volumes:
            - "../app/config/prod:/app/config"
        command: bash -c "uwsgi --ini /app/uwsgi.ini"
    server:
        build: ../server
        container_name: nginx_backend
        volumes:
            - /etc/ssl/gmbx:/etc/ssl/gmbx
            - ../logs/server-backend:/var/log/nginx
        ports:
            - "8000:8000"
            - "8443:8443"
        depends_on:
            - "application"
    frontend:
        build: ../frontend
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /etc/ssl/gmbx:/etc/ssl/gmbx
        depends_on:
            - "server"
