version: '3'

services:
    application:
        build: ../app
        container_name: game_schema_poc
        command: bash -c "uwsgi --ini /game_schema_poc/uwsgi.ini"
    server:
        build: ../server
        container_name: nginx_backend
        volumes:
            - ../ssl:/etc/ssl/gmbx
            - ../logs/server-backend:/var/log/nginx
        ports:
            - "8000:8000"
            - "8443:8443"
        depends_on:
            - "application"
    frontend:
        build: ../frontend
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ../ssl:/etc/ssl/gmbx
            depends_on:
                - "server"
