# Generated by Django 3.0.5 on 2020-05-10 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Terminal',
            new_name='SessionEnd',
        ),
    ]
