# Generated by Django 3.0.5 on 2020-05-03 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20200503_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='creator_agent_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.Agent'),
        ),
    ]
