# Generated by Django 3.0.5 on 2020-05-06 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_init', models.DateTimeField(auto_now_add=True)),
                ('creator_agent_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.Agent')),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_index', models.IntegerField()),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Session')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('agent_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='games.Agent')),
                ('display_name', models.CharField(max_length=50)),
                ('token', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_at', models.DateTimeField(auto_now_add=True)),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.State')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game')),
            ],
        ),
        migrations.CreateModel(
            name='HasRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Agent')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Role')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Session')),
            ],
        ),
        migrations.CreateModel(
            name='Does',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.HasRole')),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.State')),
            ],
        ),
        migrations.CreateModel(
            name='ActionType',
            fields=[
                ('type_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.ActionType')),
            ],
        ),
    ]
