# Generated by Django 3.0.5 on 2020-05-03 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_gameaction_gamerole'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_init', models.DateTimeField(auto_now_add=True)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_index', models.IntegerField()),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Session')),
            ],
        ),
        migrations.RenameModel(
            old_name='GameAction',
            new_name='Action',
        ),
        migrations.RenameModel(
            old_name='GameRole',
            new_name='Role',
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_at', models.DateTimeField(auto_now_add=True)),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.State')),
            ],
        ),
        migrations.CreateModel(
            name='HasRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Agent')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Role')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Session')),
            ],
        ),
        migrations.CreateModel(
            name='Does',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.HasRole')),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.State')),
            ],
        ),
    ]
