# Generated by Django 3.0.5 on 2020-05-03 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20200503_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='agent_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='games.Agent'),
        ),
    ]
